# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "edward", path: ".."

gem "slim", "~> 5.2"

gem "pandoc-ruby", "~> 2.1"

gem "mimemagic", "~> 0.4.3"

gem "asciidoctor", "~> 2.0"
